# Generated by Django 4.2.17 on 2024-12-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="created_by",),
    ]
