name: CI

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate --noinput

    - name: Run tests with coverage
      run: |
        python run_coverage.py
      env:
        MIN_COVERAGE: 80

    - name: Check test coverage
      if: ${{ failure() || steps.test_coverage.outcome == 'failure' }}
      run: |
        echo "Test coverage is below the minimum threshold."
        exit 1

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: push_reports/coverage_report.html

    - name: Notify code maintainer
      if: ${{ failure() }}
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Replace with your Slack webhook URL