name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate --noinput

    - name: Run tests with coverage
      run: |
        python run_coverage.py
      continue-on-error: true

    - name: Check coverage
      if: ${{ failure() || success() }}
      run: |
        coverage_threshold=$(python -c "import os; print(os.getenv('COVERAGE_THRESHOLD', '80'))")
        coverage_percentage=$(cat coverage.xml | grep -oP '(?<=lines-covered=")[^"]*' | head -1)
        if (( $(echo "$coverage_percentage < $coverage_threshold" | bc -l) )); then
          echo "Coverage ($coverage_percentage%) is below the minimum threshold ($coverage_threshold%)."
          exit 1
        fi

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: push_reports/coverage_report.html

    - name: Notify on failure
      if: ${{ failure() }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"text": "CI/CD pipeline failed. Please check the logs for details."}' https://hooks.slack.com/services/your-slack-webhook-url